import "./globals.css"
import Footer from "@/components/footer/footer"
import Navbar from "../components/navbar/navbar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  keywords: ['Portfolio', 'Fullstack', 'NextJS']
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Navbar/>
        <main>
          { children }
        </main>
        <Footer/>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
      </body>
    </html>
  )
}
